export type Risk="low"|"moderate"|"high"|"critical";export type Finding={category:string;label:string;severity:Risk};export type PrivacyAnalysis={protectedText:string;risk:Risk;findings:Finding[];changes:string[]};
const detectors=[
 {category:"credential",label:"Credential or secret key",severity:"critical" as const,regex:/\b(?:sk-[a-z0-9_-]{12,}|api[_ -]?key\s*[:=]\s*\S+|password\s*[:=]\s*\S+)\b/gi,replace:"[CREDENTIAL_REMOVED]"},
 {category:"email",label:"Email address",severity:"high" as const,regex:/\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b/gi,replace:"[EMAIL_1]"},
 {category:"network",label:"IP address",severity:"high" as const,regex:/\b(?:\d{1,3}\.){3}\d{1,3}\b/g,replace:"[IP_ADDRESS_1]"},
 {category:"phone",label:"Phone number",severity:"high" as const,regex:/(?<!\w)(?:\+?\d[\d\s().-]{8,}\d)(?!\w)/g,replace:"[PHONE_1]"},
 {category:"identity",label:"Named identity",severity:"high" as const,regex:/\b[Mm]y [Nn]ame [Ii]s\s+([A-Z][a-z]+(?:\s+[A-Z][a-z]+){0,2})/g,replace:"my name is [PERSON_1]"},
 {category:"organization",label:"Private organization name",severity:"high" as const,regex:/\b[Mm]y (?:company|startup|business|employer) is\s+([A-Z][\w&.-]+(?:\s+[A-Z][\w&.-]+){0,3})/g,replace:"My organization is [ORGANIZATION_1]"},
 {category:"address",label:"Street address",severity:"high" as const,regex:/\b\d{1,6}\s+(?:[A-Z][\w.-]+\s+){0,4}(?:Street|St|Road|Rd|Avenue|Ave|Lane|Ln|Drive|Dr|Boulevard|Blvd)\b/gi,replace:"[ADDRESS_1]"},
 {category:"government-id",label:"Government identifier",severity:"critical" as const,regex:/\b(?:SSN|NIN|passport(?: number)?|national id)\s*[:#-]?\s*[A-Z0-9-]{5,}\b/gi,replace:"[GOVERNMENT_IDENTIFIER_REMOVED]"},
 {category:"finance",label:"Payment card pattern",severity:"critical" as const,regex:/\b(?:\d[ -]*?){13,19}\b/g,replace:"[FINANCIAL_IDENTIFIER_REMOVED]"},
];
const secretIntent=/\b(confidential|unreleased|secret|product idea|business idea|novel mechanism|do not share|private strategy|client data|internal plan)\b/i;
const sensitiveContexts=[
 {category:"medical-context",label:"Medical or health context",regex:/\b(diagnosed with|medical record|patient record|prescription|test result|mental health)\b/i},
 {category:"legal-context",label:"Legal or dispute context",regex:/\b(lawsuit|legal case|court case|settlement agreement|attorney-client)\b/i},
 {category:"financial-context",label:"Private financial context",regex:/\b(bank statement|account balance|tax return|credit report|salary details)\b/i},
];
export function analyzePrompt(input:string,mode:"balanced"|"strict"="balanced"):PrivacyAnalysis{let protectedText=input;const findings:Finding[]=[];const changes:string[]=[];for(const detector of detectors){detector.regex.lastIndex=0;if(detector.regex.test(protectedText)){findings.push({category:detector.category,label:detector.label,severity:detector.severity});detector.regex.lastIndex=0;protectedText=protectedText.replace(detector.regex,detector.replace);changes.push(`${detector.label} was removed or replaced locally.`);}}if(secretIntent.test(input)){findings.push({category:"confidential-context",label:"Confidential idea or strategy",severity:"high"});changes.push("Distinctive secret language was generalized for the external task.");protectedText=protectedText.replace(secretIntent,"protected").replace(/\bmy\s+protected\s+product idea\b/i,"my protected concept");}for(const context of sensitiveContexts){if(context.regex.test(input)){findings.push({category:context.category,label:context.label,severity:"high"});changes.push(`${context.label} requires review before sending.`);}}if(mode==="strict"){protectedText=protectedText.replace(/\b(?:exactly|specifically|located at|working with)\b/gi,"").replace(/\s{2,}/g," ").trim();changes.push("Strict mode minimized unnecessary specificity.");}const ranks:Risk[]=["low","moderate","high","critical"];let risk:Risk=findings.length?"moderate":"low";for(const finding of findings)if(ranks.indexOf(finding.severity)>ranks.indexOf(risk))risk=finding.severity;return{protectedText,risk,findings,changes:changes.length?changes:["No sensitive transformation was necessary."]};}
