export type VaultSession={id:string;updatedAt:number;mode:"balanced"|"strict";messages:unknown[]};type Envelope={nonce:string;ciphertext:string};type Meta={id:"vault";salt:string;verifier:Envelope};
const DB_NAME="sycrely-vault",STORE_META="meta",STORE_SESSIONS="sessions",enc=new TextEncoder(),dec=new TextDecoder();const b64=(value:ArrayBuffer|Uint8Array)=>btoa(String.fromCharCode(...new Uint8Array(value)));const unb64=(value:string)=>Uint8Array.from(atob(value),c=>c.charCodeAt(0));
function db():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{const request=indexedDB.open(DB_NAME,1);request.onupgradeneeded=()=>{const database=request.result;if(!database.objectStoreNames.contains(STORE_META))database.createObjectStore(STORE_META,{keyPath:"id"});if(!database.objectStoreNames.contains(STORE_SESSIONS))database.createObjectStore(STORE_SESSIONS,{keyPath:"id"});};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
function get<T>(store:string,id:string):Promise<T|undefined>{return db().then(database=>new Promise((resolve,reject)=>{const request=database.transaction(store,"readonly").objectStore(store).get(id);request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);}));}
function put(store:string,value:unknown):Promise<void>{return db().then(database=>new Promise((resolve,reject)=>{const tx=database.transaction(store,"readwrite");tx.objectStore(store).put(value);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);}));}
async function derive(pin:string,salt:Uint8Array){const material=await crypto.subtle.importKey("raw",enc.encode(pin),"PBKDF2",false,["deriveKey"]);return crypto.subtle.deriveKey({name:"PBKDF2",salt:new Uint8Array(salt),iterations:210000,hash:"SHA-256"},material,{name:"AES-GCM",length:256},false,["encrypt","decrypt"]);}
async function encrypt(key:CryptoKey,value:unknown):Promise<Envelope>{const nonce=crypto.getRandomValues(new Uint8Array(12));const ciphertext=await crypto.subtle.encrypt({name:"AES-GCM",iv:nonce},key,enc.encode(JSON.stringify(value)));return{nonce:b64(nonce),ciphertext:b64(ciphertext)};}
async function decrypt<T>(key:CryptoKey,envelope:Envelope):Promise<T>{const plaintext=await crypto.subtle.decrypt({name:"AES-GCM",iv:unb64(envelope.nonce)},key,unb64(envelope.ciphertext));return JSON.parse(dec.decode(plaintext));}
export async function hasVault(){return Boolean(await get<Meta>(STORE_META,"vault"));}export async function createVault(pin:string){const salt=crypto.getRandomValues(new Uint8Array(16));const key=await derive(pin,salt);await put(STORE_META,{id:"vault",salt:b64(salt),verifier:await encrypt(key,{check:"sycrely-vault-v1"})});return key;}export async function unlockVault(pin:string){const meta=await get<Meta>(STORE_META,"vault");if(!meta)throw new Error("Missing vault");const key=await derive(pin,unb64(meta.salt));const check=await decrypt<{check:string}>(key,meta.verifier);if(check.check!=="sycrely-vault-v1")throw new Error("Invalid vault");return key;}export async function saveSession(key:CryptoKey,session:VaultSession){await put(STORE_SESSIONS,{id:session.id,updatedAt:session.updatedAt,payload:await encrypt(key,session)});}export async function loadSession(key:CryptoKey,id:string){const row=await get<{id:string;payload:Envelope}>(STORE_SESSIONS,id);return row?decrypt<VaultSession>(key,row.payload):undefined;}export async function deleteSession(id:string){const database=await db();await new Promise<void>((resolve,reject)=>{const tx=database.transaction(STORE_SESSIONS,"readwrite");tx.objectStore(STORE_SESSIONS).delete(id);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);});}
